---
- name: check tar installation
  apt:
    name: tar

- name: checking directory existense for {{ jdk_path }}
  file:
    path: '{{ java_home }}'
    state: directory

- name: unarchiving jdk package
  unarchive:
    src: "{{ jdk_url }}"
    dest: '{{ java_home }}'
    copy: false
    extra_opts:
      - --strip-components=1
    creates: "{{ java_home }}/bin/java"

- name: setting up environments with /etc/profile.d/java-env.sh file
  template:
    src: java.sh.j2
    dest: /etc/profile.d/java-env.sh
